### ISSUE TITLE
Is FL integrable with ESLint?

### ISSUE THREAD

**Issue by imsergiobernal** [denisraslov/structlint#12]
I would like to keep the projects simple so I would like to know if integrating this with ESLint could be viable. I never developed some kind of linters.

**Comment by denisraslov** [comment]
Your suggestion totally makes sense! I also thought about it before implementing FoldersLint.

Although, unfortunately, ESLint is a tool that allows to validate JS and TS files content (the code inside of the files), but it can't help with validation of files paths. Therefore, the FoldersLint functional couldn't be implemented as a ESLint plugin, and was implemented as a separate tool.
