### ISSUE TITLE
Windows Not Supported

### ISSUE THREAD

**Issue by mattferrin** [denisraslov/structlint#2]
I noticed that replacing the 2 occurrences of `process.cwd()` with `process.cwd().split(path.sep).join(path.posix.sep)` resolved this issue locally for me.

I visited https://shapeshed.com/writing-cross-platform-node/ first, but in the end found https://stackoverflow.com/a/63251716/1964376 to be helpful.

**Comment by denisraslov** [comment]
Thanks! I've merged [your PR](https://github.com/mattferrin/folderslint/pull/1) 👍
